import { useCallback, useRef, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { apiRequest, currentUser } from '../components/fashion-data';

export type SavedAddress={id:number;label:string;name:string;phone:string;address:string;isDefault:boolean;version:number};
const blank={label:'',name:'',phone:'',address:'',isDefault:false};
export default function AddressesScreen(){
  const router=useRouter(),insets=useSafeAreaInsets(),generation=useRef(0),lock=useRef(false);
  const [items,setItems]=useState<SavedAddress[]>([]),[editing,setEditing]=useState<SavedAddress|null>(null),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
  const load=useCallback(async()=>{const current=++generation.current;setLoading(true);setError('');try{if((await currentUser())?.role!=='user'){router.replace({pathname:'/login',params:{returnTo:'/addresses'}} as never);return;}const result=await apiRequest('/shopping/addresses');if(current===generation.current)setItems(result.items);}catch(cause){if(current===generation.current)setError(cause instanceof Error?cause.message:'Không thể tải sổ địa chỉ.');}finally{if(current===generation.current)setLoading(false);}},[router]);
  useFocusEffect(useCallback(()=>{setItems([]);setOpen(false);void load();return()=>{generation.current++;};},[load]));
  const mutate=async(path:string,method:string,body:unknown,message:string)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setSuccess('');try{await apiRequest(path,{method,body:JSON.stringify(body)});setOpen(false);setEditing(null);setSuccess(message);await load();}catch(cause){setError(cause instanceof Error?cause.message:'Không thể lưu địa chỉ.');}finally{lock.current=false;setBusy(false);}};
  return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" style={styles.root} contentContainerStyle={{padding:20,paddingTop:insets.top+20,paddingBottom:insets.bottom+40}}><View style={styles.content}>
    <Pressable accessibilityRole="button" onPress={()=>router.canGoBack()?router.back():router.replace('/profile' as never)}><Text style={styles.link}>← Tài khoản</Text></Pressable><Text style={styles.title}>Sổ địa chỉ</Text><Text style={styles.help}>Tối đa 20 địa chỉ. Địa chỉ mặc định được đề xuất khi đặt hàng; đơn cũ giữ nguyên người nhận đã xác nhận.</Text>
    {loading&&<ActivityIndicator color="#9f2438"/>}{!!error&&<><Text accessibilityRole="alert" style={styles.error}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()}><Text style={styles.link}>Tải lại sổ địa chỉ</Text></Pressable></>}{!!success&&<Text accessibilityRole="alert" style={styles.success}>{success}</Text>}
    {!loading&&!items.length&&<Text style={styles.help}>Bạn chưa lưu địa chỉ nhận hàng.</Text>}
    {!open&&<Pressable accessibilityRole="button" disabled={busy} style={styles.primary} onPress={()=>{setEditing(null);setForm(blank);setOpen(true);setSuccess('');setError('');}}><Text style={styles.primaryText}>Thêm địa chỉ</Text></Pressable>}
    {open&&<View style={styles.card}><Text style={styles.label}>{editing?'Sửa địa chỉ':'Địa chỉ mới'}</Text>{(['label','name','phone','address'] as const).map(key=><View key={key} style={{gap:6}}><Text style={styles.help}>{{label:'Tên địa chỉ',name:'Người nhận',phone:'Điện thoại',address:'Địa chỉ đầy đủ'}[key]}</Text><TextInput accessibilityLabel={{label:'Tên địa chỉ',name:'Người nhận lưu',phone:'Điện thoại lưu',address:'Địa chỉ đầy đủ'}[key]} placeholder={{label:'Nhà riêng, công ty…',name:'Họ tên người nhận',phone:'Số điện thoại',address:'Số nhà, đường, phường/xã, tỉnh/thành phố'}[key]} value={form[key]} editable={!busy} maxLength={{label:80,name:255,phone:25,address:4000}[key]} keyboardType={key==='phone'?'phone-pad':'default'} multiline={key==='address'} onChangeText={value=>setForm({...form,[key]:value})} style={styles.input}/></View>)}
    <Pressable accessibilityRole="checkbox" aria-checked={form.isDefault} accessibilityState={{checked:form.isDefault,disabled:busy||editing?.isDefault===true}} disabled={busy||editing?.isDefault===true} onPress={()=>setForm({...form,isDefault:!form.isDefault})}><Text style={styles.link}>{form.isDefault?'☑':'☐'} Đặt làm mặc định</Text></Pressable>
    <Pressable accessibilityRole="button" disabled={busy} style={styles.primary} onPress={()=>{if(!form.label.trim()||!form.name.trim()||!form.phone.trim()||!form.address.trim()){setError('Nhập đủ tên địa chỉ, người nhận, điện thoại và địa chỉ.');return;}void mutate(editing?`/shopping/addresses/${editing.id}`:'/shopping/addresses',editing?'PUT':'POST',{...form,...(editing?{expectedVersion:editing.version}:{})},'Đã lưu địa chỉ.');}}><Text style={styles.primaryText}>{busy?'Đang lưu…':'Lưu địa chỉ'}</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={()=>setOpen(false)}><Text style={styles.link}>Hủy chỉnh sửa</Text></Pressable></View>}
    {items.map(item=><View key={item.id} style={styles.card}><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}><Text style={styles.label}>{item.label}</Text>{item.isDefault&&<Text style={styles.success}>Mặc định</Text>}</View><Text>{item.name} · {item.phone}</Text><Text style={styles.help}>{item.address}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:16}}><Pressable accessibilityRole="button" accessibilityLabel={`Sửa địa chỉ ${item.label}`} disabled={busy} onPress={()=>{setEditing(item);setForm({label:item.label,name:item.name,phone:item.phone,address:item.address,isDefault:item.isDefault});setOpen(true);setError('');setSuccess('');}}><Text style={styles.link}>Sửa</Text></Pressable>{!item.isDefault&&<Pressable accessibilityRole="button" accessibilityLabel={`Mặc định ${item.label}`} disabled={busy} onPress={()=>void mutate(`/shopping/addresses/${item.id}/default`,'PUT',{expectedVersion:item.version},'Đã đổi địa chỉ mặc định.')}><Text style={styles.link}>Đặt mặc định</Text></Pressable>}<Pressable accessibilityRole="button" accessibilityLabel={`Xóa địa chỉ ${item.label}`} disabled={busy} onPress={()=>void mutate(`/shopping/addresses/${item.id}`,'DELETE',{expectedVersion:item.version},'Đã xóa địa chỉ; đơn cũ không thay đổi.')}><Text style={styles.link}>Xóa</Text></Pressable></View></View>)}
  </View></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#f7f5ef'},content:{width:'100%',maxWidth:760,alignSelf:'center',gap:16},title:{fontFamily:'Inter',fontSize:26,fontWeight:'700',color:'#302524'},label:{fontFamily:'Inter',fontWeight:'700',color:'#302524'},help:{fontFamily:'Inter',color:'#81776f',lineHeight:21},card:{padding:18,borderRadius:16,backgroundColor:'#fffefa',borderWidth:1,borderColor:'#e9e4dc',gap:12},input:{borderWidth:1,borderColor:'#ded5cc',borderRadius:10,padding:14,fontFamily:'Inter',minHeight:48},link:{color:'#9f2438',paddingVertical:10,fontFamily:'Inter'},primary:{padding:16,borderRadius:12,backgroundColor:'#9f2438',alignItems:'center'},primaryText:{fontFamily:'Inter',fontWeight:'700',color:'#fff'},error:{color:'#9f2438'},success:{color:'#37675b'}});
