import { Image } from 'expo-image';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { FashionHeader } from '@/components/fashion-header';
import { news, trends } from '@/components/fashion-data';
import { useRouter } from 'expo-router';
import Page from '@/components/Page';
import SectionTitle from '@/components/SectionTitle';
import { palette } from '@/components/theme';
export default function NewsScreen() {
	const router = useRouter();
	return <View style={styles.root}><FashionHeader /><Page title="Tin tức"><SectionTitle>Tin tức thời trang & làm đẹp</SectionTitle>{news.map(item => <View style={styles.card} key={item.id}><Image source={item.image} style={styles.image} contentFit="cover" /><View style={styles.body}><Text style={styles.badge}>MỚI NHẤT</Text><Text style={styles.heading}>{item.title}</Text><Text style={styles.description}>{item.description}</Text><Text style={styles.link}>Đọc thêm →</Text></View></View>)}<View style={styles.banner}><Image source="https://images.unsplash.com/photo-1521336575822-6da63fb45455?w=1200" style={StyleSheet.absoluteFill} contentFit="cover" /><View style={styles.overlay}><Text style={styles.bannerTitle}>Fashion Haven 2025</Text><Text style={styles.bannerText}>Tỏa sáng cá tính riêng của bạn.</Text><Pressable onPress={() => router.push('/products' as never)}><Text style={styles.bannerLink}>Khám phá sản phẩm →</Text></Pressable></View></View><SectionTitle>Xu hướng nổi bật</SectionTitle>{trends.map(item => <View style={styles.trendCard} key={item.id}><Image source={item.image} style={styles.trendImage} contentFit="cover" /><View style={styles.body}><Text style={styles.heading}>{item.title}</Text><Text style={styles.description}>{item.description}</Text></View></View>)}</Page></View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, card: { backgroundColor: '#fff', borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: palette.line, marginBottom: 18 }, image: { height: 190, width: '100%' }, body: { padding: 16 }, badge: { color: palette.red, fontSize: 11, fontWeight: '900', letterSpacing: 1 }, heading: { fontSize: 21, color: palette.ink, fontWeight: '800', marginVertical: 8 }, description: { color: palette.muted, lineHeight: 21 }, link: { color: palette.red, fontWeight: '800', marginTop: 14 }, banner: { height: 230, borderRadius: 10, overflow: 'hidden', marginVertical: 12 }, overlay: { flex: 1, justifyContent: 'flex-end', padding: 18, backgroundColor: 'rgba(0,0,0,0.4)' }, bannerTitle: { color: '#fff', fontWeight: '900', fontSize: 26 }, bannerText: { color: '#fff', marginVertical: 5 }, bannerLink: { color: '#ffd7cf', fontWeight: '800' }, trendCard: { borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: palette.line, backgroundColor: '#fff', marginBottom: 18 }, trendImage: { width: '100%', height: 220 } });