const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const express = require('express');

async function serveBuild(directory, expo = false) {
  const root = path.resolve(__dirname, '../../', directory);
  await fs.access(path.join(root, 'index.html'));
  const app = express();
  app.use(express.static(root, { extensions: ['html'] }));
  app.use((req, res) => {
    const filename = expo && /^\/product\/[^/]+$/.test(req.path) ? 'product/[id].html' : expo ? '+not-found.html' : 'index.html';
    res.sendFile(path.join(root, filename));
  });
  const server = await new Promise(resolve => { const server = app.listen(0, '127.0.0.1', () => resolve(server)); });
  return { url: `http://127.0.0.1:${server.address().port}`, close: () => new Promise(resolve => server.close(resolve)) };
}

exports.runBrowser = async ({ base, productId, customerId, prisma }) => {
  const { chromium } = require(process.env.PLAYWRIGHT_MODULE);
  // Serve real built apps locally; bundler startup is outside the business test.
  const customerWeb = await serveBuild('FE/dist', true);
  const adminWeb = await serveBuild('admin_web/dist');
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const errors = [];
  context.on('page', page => page.on('pageerror', error => errors.push(error.message)));
  // Frontends are real built apps. Every API request hits the real
  // Express server and isolated MySQL, with no fabricated HTTP responses.
  const routeApi = async route => {
    const original = new URL(route.request().url());
    const suffix = original.pathname.slice(original.pathname.indexOf('/api') + 4) + original.search;
    const response = await route.fetch({ url: base + suffix });
    await route.fulfill({ response, headers: { ...response.headers(), 'access-control-allow-origin': '*', 'access-control-allow-headers': 'Content-Type,Authorization,Idempotency-Key' } });
  };
  await context.route('**/api/**', routeApi);
  const directory = path.resolve(__dirname, '../test-artifacts');
  await fs.mkdir(directory, { recursive: true });
  const page = await context.newPage();
  let activePage = page;
  page.setDefaultTimeout(30000);
  page.setDefaultNavigationTimeout(60000);
  try {
    console.log('Browser: customer login');
    await page.goto(`${customerWeb.url}/login?returnTo=/cart`, { waitUntil: 'domcontentloaded' });
    await page.getByPlaceholder('Email hoặc Tên đăng nhập').fill('synthetic@example.invalid');
    await page.getByPlaceholder('Mật khẩu', { exact: true }).fill('NewCustomerPass1!');
    await page.getByText('ĐĂNG NHẬP', { exact: true }).click();
    await page.waitForURL(/\/cart$/);
    await page.getByText('Giỏ hàng đang trống', { exact: true }).waitFor();
    await page.goto(`${customerWeb.url}/product/${productId}`, { waitUntil: 'domcontentloaded' });
    await page.getByText('Synthetic garment', { exact: true }).first().waitFor();
    console.log('Browser: customer checkout');
    await page.getByText('Mua ngay', { exact: true }).click();
    await page.getByLabel('Họ tên người nhận').fill('Browser synthetic customer');
    await page.getByLabel('Số điện thoại nhận hàng').fill('0900000000');
    await page.getByLabel('Địa chỉ nhận hàng').fill('Synthetic browser test address');
    await page.getByText('Đặt hàng COD', { exact: true }).click();
    await page.waitForURL(/\/orders$/);
    const created = await prisma.phieuXuat.findFirstOrThrow({ where: { MaKhachHang: customerId, TenNguoiNhan: 'Browser synthetic customer' }, orderBy: { MaPhieuXuat: 'desc' } });
    assert.equal(created.TongTien, 120000);
    await page.getByText('Synthetic garment × 1', { exact: true }).first().waitFor();
    await page.screenshot({ path: path.join(directory, 'customer-orders-mobile.png'), fullPage: true });

    console.log('Browser: admin fulfillment');
    const admin = await context.newPage();
    activePage = admin;
    await admin.setViewportSize({ width: 1440, height: 1000 });
    await admin.goto(`${adminWeb.url}/login`, { waitUntil: 'domcontentloaded' });
    await admin.getByLabel('Tên đăng nhập').fill('test-admin');
    await admin.getByLabel('Mật khẩu', { exact: true }).fill('TestPassword1!');
    await admin.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
    await admin.getByRole('button', { name: 'Quản lý đơn hàng', exact: true }).click();
    const row = admin.getByRole('row').filter({ hasText: 'Browser synthetic customer' });
    await row.getByRole('button', { name: 'Xem & xử lý' }).click();
    let dialog = admin.getByRole('dialog');
    await dialog.getByRole('button', { name: 'Đang đóng gói', exact: true }).click();
    await dialog.getByText('Đang đóng gói · Chưa thanh toán', { exact: true }).waitFor();
    await dialog.getByLabel('Đơn vị giao hàng').fill('Synthetic UI courier');
    await dialog.getByLabel('Mã vận đơn').fill('BROWSER-TEST-001');
    await dialog.getByRole('button', { name: 'Đang giao', exact: true }).click();
    await dialog.getByText('Đang giao · Chưa thanh toán', { exact: true }).waitFor();
    await dialog.getByRole('button', { name: 'Đã giao', exact: true }).click();
    await dialog.getByText('Đã giao · Chưa thanh toán', { exact: true }).waitFor();
    await dialog.getByLabel('Lý do hủy / căn cứ đối soát').fill('Synthetic UI COD receipt');
    await dialog.getByRole('button', { name: 'Xác nhận đã nhận tiền COD' }).click();
    await dialog.getByText('Đã giao · Đã đối soát', { exact: true }).waitFor();
    await admin.screenshot({ path: path.join(directory, 'admin-delivered-order.png'), fullPage: true });
    const delivered = await prisma.phieuXuat.findUniqueOrThrow({ where: { MaPhieuXuat: created.MaPhieuXuat } });
    assert.equal(delivered.TrangThai, 'DELIVERED'); assert.equal(delivered.TrangThaiThanhToan, 'PAID');
    console.log('Browser: variant inventory editor');
    await dialog.getByRole('button', { name: 'Đóng chi tiết', exact: true }).click();
    await admin.getByRole('button', { name: 'Sản phẩm & Tồn kho', exact: true }).click();
    await admin.getByRole('button', { name: 'Sửa sản phẩm Synthetic garment', exact: true }).click();
    dialog = admin.getByRole('dialog');
    const before = await prisma.sanPham.findUniqueOrThrow({ where: { MaSanPham: productId }, include: { bienThes: { orderBy: { MaBienThe: 'asc' } } } });
    await dialog.getByLabel(/^Tồn sau điều chỉnh/).first().fill(String(before.bienThes[0].SoLuong + 2));
    await dialog.getByLabel(/^Lý do điều chỉnh/).fill('Synthetic browser inventory count');
    await dialog.getByRole('button', { name: 'Lưu sản phẩm', exact: true }).click();
    await dialog.waitFor({ state: 'hidden' });
    const edited = await prisma.sanPham.findUniqueOrThrow({ where: { MaSanPham: productId }, include: { bienThes: { orderBy: { MaBienThe: 'asc' } } } });
    assert.equal(edited.SoLuong, before.SoLuong + 2); assert.equal(edited.bienThes[0].SoLuong, before.bienThes[0].SoLuong + 2);
    assert.equal(edited.bienThes[0].KichCo, before.bienThes[0].KichCo);
    assert.equal(edited.Anh || null, before.Anh || null);
    await admin.screenshot({ path: path.join(directory, 'admin-variant-stock.png'), fullPage: true });

    console.log('Browser: draft receipt and stock posting');
    await admin.getByRole('button', { name: 'Phiếu nhập hàng', exact: true }).click();
    await admin.getByRole('button', { name: 'Tạo phiếu nhập', exact: true }).click();
    dialog = admin.getByRole('dialog');
    await dialog.getByRole('combobox').nth(0).selectOption({ label: 'Test supplier' });
    await dialog.getByRole('combobox').nth(1).selectOption({ label: 'Test warehouse' });
    await dialog.getByRole('button', { name: 'Thêm dòng hàng', exact: true }).click();
    await dialog.getByLabel('Sản phẩm dòng 1', { exact: true }).selectOption(String(productId));
    await dialog.getByLabel('Biến thể dòng 1', { exact: true }).selectOption(String(edited.bienThes[0].MaBienThe));
    await dialog.getByLabel('Số lượng dòng 1', { exact: true }).fill('3');
    await dialog.getByLabel('Giá mua dòng 1', { exact: true }).fill('51000');
    await dialog.getByRole('button', { name: 'Lưu phiếu nháp', exact: true }).click();
    await dialog.waitFor({ state: 'hidden' });
    const receipt = await prisma.phieuNhap.findFirstOrThrow({ where: { TrangThai: 'DRAFT' }, orderBy: { MaPhieuNhap: 'desc' } });
    assert.equal(receipt.TongTien, 153000);
    assert.equal((await prisma.sanPham.findUniqueOrThrow({ where: { MaSanPham: productId } })).SoLuong, edited.SoLuong);
    await admin.getByRole('row').filter({ hasText: `#${receipt.MaPhieuNhap}` }).getByRole('button', { name: 'Xem phiếu', exact: true }).click();
    dialog = admin.getByRole('dialog');
    await dialog.getByLabel('Căn cứ kiểm nhận / lý do hủy').fill('Synthetic browser receiving record');
    await dialog.getByRole('button', { name: 'Đã kiểm nhận · Cộng kho', exact: true }).click();
    await dialog.waitFor({ state: 'hidden' });
    const received = await prisma.sanPham.findUniqueOrThrow({ where: { MaSanPham: productId }, include: { bienThes: { orderBy: { MaBienThe: 'asc' } } } });
    assert.equal(received.SoLuong, edited.SoLuong + 3); assert.equal(received.bienThes[0].SoLuong, edited.bienThes[0].SoLuong + 3);
    assert.equal((await prisma.phieuNhap.findUniqueOrThrow({ where: { MaPhieuNhap: receipt.MaPhieuNhap } })).TrangThai, 'RECEIVED');
    await admin.screenshot({ path: path.join(directory, 'admin-received-import.png'), fullPage: true });
    console.log('Browser: new product with per-variant opening quantities');
    await admin.getByRole('button', { name: 'Sản phẩm & Tồn kho', exact: true }).click();
    await admin.getByRole('button', { name: 'Thêm Sản phẩm', exact: true }).click();
    dialog = admin.getByRole('dialog');
    await dialog.getByLabel(/^Tên sản phẩm/).fill('Browser created variants');
    await dialog.getByLabel(/^Danh mục/).selectOption({ label: 'Test category' });
    await dialog.getByLabel(/^Giá bán mặc định/).fill('50000');
    await dialog.getByLabel(/^Giá nhập tham chiếu/).fill('25000');
    await dialog.getByLabel(/^Kho quản lý/).selectOption({ label: 'Test warehouse' });
    await dialog.getByLabel(/^Nhà cung cấp/).selectOption({ label: 'Test supplier' });
    await dialog.getByRole('button', { name: '+ Thêm biến thể', exact: true }).click();
    await dialog.getByLabel('Màu sắc', { exact: true }).first().fill('Đen');
    await dialog.getByLabel('SKU', { exact: true }).first().fill('UI-BLACK-ONE');
    await dialog.getByLabel(/^Tồn ban đầu/).first().fill('5');
    await dialog.getByRole('button', { name: '+ Thêm biến thể', exact: true }).click();
    await dialog.getByLabel('Màu sắc', { exact: true }).nth(1).fill('Trắng');
    await dialog.getByLabel('SKU', { exact: true }).nth(1).fill('UI-WHITE-ONE');
    await dialog.getByLabel(/^Tồn ban đầu/).nth(1).fill('3');
    await dialog.getByRole('button', { name: 'Lưu sản phẩm', exact: true }).click();
    await dialog.waitFor({ state: 'hidden' });
    const newProduct = await prisma.sanPham.findFirstOrThrow({ where: { TenSanPham: 'Browser created variants' }, include: { bienThes: { orderBy: { MaBienThe: 'asc' } } } });
    assert.equal(newProduct.SoLuong, 8); assert.deepEqual(newProduct.bienThes.map(v => v.SoLuong), [5, 3]);
    assert.equal(newProduct.DonGiaBan, 50000);
    await admin.screenshot({ path: path.join(directory, 'admin-new-product-variants.png'), fullPage: true });
    console.log('Browser: customer tracks delivery and courier details');
    activePage = page;
    await page.reload({ waitUntil: 'domcontentloaded' });
    const customerCard = page.getByText(`Đơn #${String(created.MaPhieuXuat).padStart(5, '0')}`, { exact: true }).locator('../..');
    await customerCard.getByText('Đã giao', { exact: true }).waitFor();
    await customerCard.getByText('Xem chi tiết', { exact: true }).click();
    await customerCard.getByText(/BROWSER-TEST-001/).waitFor();
    await page.screenshot({ path: path.join(directory, 'customer-delivery-details-mobile.png'), fullPage: true });

    console.log('Browser: staff mobile permissions');
    const staffContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
    staffContext.on('page', page => page.on('pageerror', error => errors.push(error.message)));
    await staffContext.route('**/api/**', routeApi);
    const staff = await staffContext.newPage(); activePage = staff;
    await staff.goto(`${adminWeb.url}/login`, { waitUntil: 'domcontentloaded' });
    await staff.getByLabel('Tên đăng nhập').fill('test-staff');
    await staff.getByLabel('Mật khẩu', { exact: true }).fill('StaffPassword1!');
    await staff.getByRole('button', { name: 'Đăng nhập', exact: true }).click();
    await staff.getByRole('heading', { name: 'Quản lý đơn hàng', exact: true }).waitFor();
    const mobileNavigation = staff.getByRole('combobox', { name: /^Chức năng/ });
    assert.deepEqual(await mobileNavigation.locator('option').evaluateAll(options => options.map(option => option.value).sort()), ['orders', 'products']);
    await mobileNavigation.selectOption('products');
    await staff.getByRole('heading', { name: 'Sản phẩm & Tồn kho', exact: true }).waitFor();
    await staff.getByText('Chỉ xem', { exact: true }).first().waitFor();
    assert.equal(await staff.getByRole('button', { name: 'Thêm Sản phẩm', exact: true }).count(), 0);
    assert.equal(await staff.getByRole('button', { name: /^Sửa sản phẩm/ }).count(), 0);
    await staff.screenshot({ path: path.join(directory, 'staff-catalog-mobile.png'), fullPage: true });
    await staffContext.close();
    assert.deepEqual(errors, []);
  } catch (error) {
    await activePage.screenshot({ path: path.join(directory, 'browser-failure.png'), fullPage: true }).catch(() => {});
    throw error;
  } finally { await browser.close(); await customerWeb.close(); await adminWeb.close(); }
};
