const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');

// Called by browser.cjs only against the disposable integration database.
exports.runCustomerBrowser = async ({ admin, page, customerUrl, prisma, directory }) => {
  const database = await prisma.$queryRawUnsafe('SELECT DATABASE() AS name');
  assert.match(database[0].name, /^fashionhaven_test_\d+_[a-f0-9]{8}$/);
  console.log('Browser: paginated customer management, account audit and credentials');
  await admin.getByRole('button', { name: 'Khách hàng', exact: true }).click();
  await admin.getByRole('heading', { name: 'Khách hàng & tài khoản', exact: true }).waitFor();
  await admin.getByLabel('Tìm khách hàng').fill('account-ui@example.invalid');
  await admin.getByRole('button', { name: 'Tìm kiếm', exact: true }).click();
  const customerRow = admin.getByRole('row').filter({ hasText: 'account-ui@example.invalid' });
  await customerRow.waitFor();
  assert.equal(await admin.getByRole('columnheader', { name: 'Mật khẩu', exact: true }).count(), 0);
  await customerRow.getByRole('button', { name: 'Xem & quản lý', exact: true }).click();
  let detail = admin.getByRole('dialog', { name: 'Account UI fixture', exact: true });
  await detail.getByRole('heading', { name: 'Nhật ký tài khoản', exact: true }).waitFor();
  await detail.getByRole('button', { name: 'Cấp mật khẩu mới', exact: true }).click();
  let action = admin.getByRole('dialog', { name: 'Cấp mật khẩu mới', exact: true });
  await action.getByLabel('Mật khẩu mới', { exact: true }).fill('BrowserGranted1!');
  await action.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('BrowserGranted1!');
  await action.getByRole('button', { name: 'Đóng', exact: true }).click();
  await detail.getByRole('button', { name: 'Cấp mật khẩu mới', exact: true }).click();
  action = admin.getByRole('dialog', { name: 'Cấp mật khẩu mới', exact: true });
  assert.equal(await action.getByLabel('Mật khẩu mới', { exact: true }).inputValue(), '');
  await action.getByLabel('Mật khẩu mới', { exact: true }).fill('BrowserGranted1!');
  await action.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('BrowserGranted1!');
  await action.getByLabel('Lý do thao tác').fill('Synthetic browser support request');
  await action.getByRole('button', { name: 'Xác nhận & lưu', exact: true }).click();
  await action.waitFor({ state: 'hidden' });
  detail = admin.getByRole('dialog', { name: 'Account UI fixture', exact: true });
  await detail.getByText('Synthetic browser support request', { exact: true }).waitFor();
  await detail.getByRole('button', { name: 'Ngưng tài khoản', exact: true }).click();
  action = admin.getByRole('dialog', { name: 'Ngưng tài khoản', exact: true });
  await action.getByLabel('Lý do thao tác').fill('Synthetic browser account suspension');
  await action.getByRole('button', { name: 'Xác nhận & lưu', exact: true }).click();
  await action.waitFor({ state: 'hidden' });
  await detail.getByRole('button', { name: 'Mở lại tài khoản', exact: true }).waitFor();
  const account = await prisma.khachHang.findUniqueOrThrow({ where: { Email: 'account-ui@example.invalid' } });
  assert.equal(account.Status, 'DISABLED');
  await detail.getByRole('button', { name: 'Mở lại tài khoản', exact: true }).click();
  action = admin.getByRole('dialog', { name: 'Mở lại tài khoản', exact: true });
  await action.getByLabel('Lý do thao tác').fill('Synthetic browser account reactivation');
  await action.getByRole('button', { name: 'Xác nhận & lưu', exact: true }).click();
  await action.waitFor({ state: 'hidden' });
  await detail.getByRole('button', { name: 'Sửa hồ sơ', exact: true }).click();
  action = admin.getByRole('dialog', { name: 'Cập nhật hồ sơ', exact: true });
  await action.getByLabel('Điện thoại', { exact: true }).fill('0901111111');
  await action.getByLabel('Lý do thao tác').fill('Synthetic browser contact correction');
  await action.getByRole('button', { name: 'Xác nhận & lưu', exact: true }).click();
  await action.waitFor({ state: 'hidden' });
  await detail.getByText('0901111111', { exact: true }).waitFor();
  await admin.screenshot({ path: path.join(directory, 'admin-customer-account-audit.png'), fullPage: true });
  await detail.getByRole('button', { name: 'Đóng', exact: true }).click();
  await admin.setViewportSize({ width: 390, height: 844 });
  await admin.screenshot({ path: path.join(directory, 'admin-customers-mobile.png'), fullPage: true });
  assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true);
  await admin.setViewportSize({ width: 1440, height: 1000 });

  console.log('Browser: create customer and recover password through real FE forms');
  await admin.getByRole('button', { name: 'Thêm khách hàng', exact: true }).click();
  action = admin.getByRole('dialog', { name: 'Tạo tài khoản khách hàng', exact: true });
  await action.getByLabel('Họ tên', { exact: true }).fill('Browser account customer');
  await action.getByLabel('Email', { exact: true }).fill('browser-customer@example.invalid');
  await action.getByLabel('Mật khẩu mới', { exact: true }).fill('BrowserInitial1!');
  await action.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('BrowserInitial1!');
  await action.getByRole('button', { name: 'Xác nhận & lưu', exact: true }).click();
  await action.waitFor({ state: 'hidden' });
  const created = await prisma.khachHang.findUniqueOrThrow({ where: { Email: 'browser-customer@example.invalid' } });
  assert.equal(created.Status, 'ACTIVE'); assert.match(created.MatKhau, /^\$2[ab]\$/);
  const config = { mode: process.env.RESET_DELIVERY_MODE, url: process.env.CUSTOMER_WEB_URL };
  const { resetOutboxFile } = require('../src/services/passwordRecovery');
  let outboxFile;
  try {
    delete process.env.RESET_DELIVERY_MODE; delete process.env.CUSTOMER_WEB_URL;
    await page.goto(`${customerUrl}/login`, { waitUntil: 'domcontentloaded' });
    await page.getByText('Quên mật khẩu?', { exact: true }).click();
    await page.waitForURL(/\/forgot-password$/);
    await page.getByLabel('Email đăng ký', { exact: true }).fill('browser-customer@example.invalid');
    await page.getByText('Gửi liên kết khôi phục', { exact: true }).click();
    await page.getByText('Dịch vụ gửi liên kết chưa sẵn sàng. Vui lòng liên hệ cửa hàng.', { exact: true }).waitFor();
    process.env.RESET_DELIVERY_MODE = 'file'; process.env.CUSTOMER_WEB_URL = customerUrl;
    await page.getByText('Gửi liên kết khôi phục', { exact: true }).click();
    await page.getByText('Nếu tài khoản đủ điều kiện, liên kết đặt lại mật khẩu sẽ được gửi. Vui lòng kiểm tra hộp thư hoặc liên hệ cửa hàng.', { exact: true }).waitFor();
    const record = await prisma.passwordReset.findFirstOrThrow({ where: { CustomerId: created.MaKhachHang, UsedAt: null }, orderBy: { Id: 'desc' } });
    outboxFile = resetOutboxFile(record.Id);
    const link = new URL(JSON.parse(await fs.readFile(outboxFile, 'utf8')).link);
    await page.goto(`${customerUrl}${link.pathname}${link.search}`, { waitUntil: 'domcontentloaded' });
    await page.getByLabel('Mật khẩu mới', { exact: true }).fill('BrowserRecovered1!');
    await page.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('MismatchPassword1!');
    await page.getByText('Lưu mật khẩu mới', { exact: true }).click();
    await page.getByText('Mật khẩu xác nhận chưa khớp.', { exact: true }).waitFor();
    await page.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('BrowserRecovered1!');
    await page.getByText('Lưu mật khẩu mới', { exact: true }).click();
    await page.getByText('Đã đổi mật khẩu và thu hồi phiên cũ. Vui lòng đăng nhập lại.', { exact: true }).waitFor();
    assert.ok((await prisma.passwordReset.findUniqueOrThrow({ where: { Id: record.Id } })).UsedAt);
    await page.screenshot({ path: path.join(directory, 'customer-password-recovered-mobile.png'), fullPage: true });
    await page.goto(`${customerUrl}${link.pathname}${link.search}`, { waitUntil: 'domcontentloaded' });
    await page.getByLabel('Mật khẩu mới', { exact: true }).fill('BrowserRecovered2!');
    await page.getByLabel('Xác nhận mật khẩu', { exact: true }).fill('BrowserRecovered2!');
    await page.getByText('Lưu mật khẩu mới', { exact: true }).click();
    await page.getByText('Liên kết không hợp lệ, đã dùng hoặc hết hạn. Vui lòng yêu cầu liên kết mới.', { exact: true }).waitFor();
    await page.goto(`${customerUrl}/login`, { waitUntil: 'domcontentloaded' });
    await page.getByPlaceholder('Email hoặc Tên đăng nhập').fill('browser-customer@example.invalid');
    await page.getByPlaceholder('Mật khẩu', { exact: true }).fill('BrowserRecovered1!');
    await page.getByText('ĐĂNG NHẬP', { exact: true }).click();
    await page.waitForURL(`${customerUrl}/`);
  } finally {
    if (outboxFile) await fs.rm(outboxFile, { force: true });
    if (config.mode === undefined) delete process.env.RESET_DELIVERY_MODE; else process.env.RESET_DELIVERY_MODE = config.mode;
    if (config.url === undefined) delete process.env.CUSTOMER_WEB_URL; else process.env.CUSTOMER_WEB_URL = config.url;
  }
};
