type Stats = { products: number; users: number; orders: number; revenue: number; collected: number; statuses: { status: string; count: number; total: number }[] };
const labels: Record<string, string> = { PENDING: 'Chờ xác nhận', PROCESSING: 'Đang đóng gói', SHIPPING: 'Đang giao', DELIVERED: 'Đã giao', CANCELLED: 'Đã hủy' };
const money = (value: number) => `${value.toLocaleString('vi-VN')} đ`;
export default function DashboardView({ stats, orders, fetchedAt, onOpenOrders }: { stats: Stats; orders: any[]; fetchedAt: string; onOpenOrders: () => void }) {
  return <section className="space-y-6">
    <div><p className="text-xs tracking-widest text-red-700 uppercase mb-2">Fashion Haven · Hoạt động cửa hàng</p><h1 className="font-serif font-bold text-3xl">Tổng quan kinh doanh</h1><p className="text-sm text-gray-500 mt-2">Toàn bộ dữ liệu hiện có · Cập nhật {new Date(fetchedAt).toLocaleString('vi-VN')}</p></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['Giá trị đơn đã giao', money(stats.revenue), 'Tổng giá trị bán hàng đã giao; chưa trừ hoàn trả'], ['Tiền COD đã đối soát', money(stats.collected), 'Chỉ gồm đơn đã giao và xác nhận thu tiền'], ['Tổng đơn hàng', stats.orders, 'Bao gồm các đơn đã hủy để giữ lịch sử'], ['Sản phẩm / Khách hàng', `${stats.products} / ${stats.users}`, 'Số hồ sơ thực tế trong database']].map(([label, value, hint]) => <div key={String(label)} className="bg-white rounded-2xl border p-5"><p className="text-sm font-semibold text-gray-500">{label}</p><p className="text-2xl font-bold mt-4">{value}</p><p className="text-xs text-gray-500 mt-3">{hint}</p></div>)}</div>
    <div className="grid lg:grid-cols-3 gap-5"><div className="bg-white border rounded-2xl p-5"><h2 className="font-bold text-lg mb-4">Trạng thái đơn hàng</h2>{stats.statuses.length === 0 ? <p className="text-gray-500 text-sm">Chưa có đơn hàng.</p> : stats.statuses.map((group, index) => <div className="mb-4" key={`${group.status}-${index}`}><div className="flex justify-between text-sm mb-1"><span>{labels[group.status] ?? group.status}</span><span className="font-semibold">{group.count}</span></div><div className="h-2 rounded bg-gray-100"><div className="h-2 rounded bg-[#b6152b]" style={{ width: `${stats.orders ? group.count / stats.orders * 100 : 0}%` }} /></div></div>)}</div>
      <div className="lg:col-span-2 bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b flex justify-between gap-3"><h2 className="text-lg font-bold">Đơn gần đây</h2><button onClick={onOpenOrders} className="text-red-700 text-sm underline">Mở quản lý đơn</button></div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-gray-50"><tr>{['Đơn', 'Khách hàng', 'Giá trị', 'Trạng thái'].map(label => <th className="p-4" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{orders.slice(0, 8).map(order => <tr key={order.id}><td className="p-4">#{order.id}</td><td className="p-4">{order.customerName}</td><td className="p-4 font-semibold">{money(order.total)}</td><td className="p-4">{labels[order.status] ?? order.status}</td></tr>)}{orders.length === 0 && <tr><td colSpan={4} className="p-8 text-center text-gray-500">Chưa có đơn hàng.</td></tr>}</tbody></table></div></div>
    </div>
  </section>;
}
