import React, { useState } from 'react';
interface Props { imports: any[]; }
export default function ImportsView({ imports }: Props) {
  const [search, setSearch] = useState('');
  const filtered = imports.filter(i => (i.supplierName||'').toLowerCase().includes(search.toLowerCase()) || String(i.id||'').includes(search));
  const totalValue = imports.reduce((s,i)=>s+(i.total||0),0);
  return (
    <div className="flex flex-col w-full pb-10">
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-6">
        <div><h1 className="text-3xl font-bold text-gray-800 font-serif mb-1">Quản lý Phiếu nhập</h1><p className="text-sm text-gray-500">Theo dõi các đợt nhập hàng từ nhà cung cấp vào kho.</p></div>
        <button className="flex items-center gap-2 px-5 py-2.5 bg-green-700 text-white rounded-xl text-sm font-bold shadow-md hover:bg-green-800"><span className="material-symbols-outlined text-base">add</span> Tạo phiếu nhập</button>
      </div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{[{label:'Tổng phiếu nhập',value:imports.length,sub:'Tháng này',icon:'description',color:'text-green-600',bg:'bg-green-50'},{label:'Tổng giá trị nhập',value:totalValue.toLocaleString('vi-VN')+' đ',sub:'+24% vs tháng trước',icon:'payments',color:'text-blue-600',bg:'bg-blue-50'},{label:'Chờ kiểm duyệt',value:imports.filter(i=>i.status==='Chờ kiểm duyệt').length,sub:'Cần phê duyệt',icon:'pending',color:'text-yellow-600',bg:'bg-yellow-50'},{label:'Đã hoàn thành',value:imports.filter(i=>i.status==='Đã hoàn thành').length,sub:'Đã vào kho',icon:'check_circle',color:'text-green-600',bg:'bg-green-50'}].map((c,i)=>(<div key={i} className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm"><div className="flex items-start justify-between mb-3"><span className="text-xs font-bold text-gray-500 uppercase tracking-wider leading-tight">{c.label}</span><div className={`w-9 h-9 rounded-xl ${c.bg} flex items-center justify-center ${c.color} shrink-0`}><span className="material-symbols-outlined text-xl">{c.icon}</span></div></div><div className="text-2xl font-bold text-gray-800 mb-1">{c.value}</div><div className="text-xs text-gray-500">{c.sub}</div></div>))}</div>
      <div className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden"><div className="flex gap-3 p-4 border-b border-gray-100"><div className="relative flex-1 max-w-sm"><span className="material-symbols-outlined absolute left-3 top-2.5 text-gray-400 text-xl">search</span><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-green-400" placeholder="Tìm theo mã, NCC..."/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-400 text-xs font-bold uppercase tracking-wider border-b border-gray-100"><tr><th className="py-4 px-5">Mã PN</th><th className="py-4 px-5">Nhân viên</th><th className="py-4 px-5">Nhà cung cấp</th><th className="py-4 px-5">Ngày nhập</th><th className="py-4 px-5 text-right">Tổng tiền</th><th className="py-4 px-5">Trạng thái</th></tr></thead><tbody className="text-gray-800 divide-y divide-gray-50">{filtered.map((imp,idx)=>(<tr key={idx} className="hover:bg-green-50/30 transition-colors"><td className="py-4 px-5 font-bold text-green-700">PN{String(imp.id||idx).padStart(5,'0')}</td><td className="py-4 px-5 text-gray-600">{imp.employeeName||'—'}</td><td className="py-4 px-5 font-semibold">{imp.supplierName||'—'}</td><td className="py-4 px-5 text-gray-500">{imp.date||'—'}</td><td className="py-4 px-5 text-right font-bold">{(imp.total||0).toLocaleString('vi-VN')} đ</td><td className="py-4 px-5"><span className="inline-block px-2.5 py-1 bg-green-50 text-green-700 text-xs font-bold rounded-full">{imp.status||'Đã hoàn thành'}</span></td></tr>))}{filtered.length===0&&<tr><td colSpan={6} className="py-12 text-center text-gray-400"><span className="material-symbols-outlined text-5xl block mb-2 opacity-30">inventory</span>Chưa có phiếu nhập nào.</td></tr>}</tbody></table></div><div className="p-4 flex items-center justify-between text-sm text-gray-500 border-t border-gray-100"><span>Hiển thị {filtered.length}/{imports.length} phiếu</span></div></div>
    </div>
  );
}
