import Icon from './Icon';
import React, { useState } from 'react';
interface Props { suppliers: any[]; onSave?: (s: any)=>void; onDelete?: (id: number)=>void; }
export default function SuppliersView({ suppliers, onSave, onDelete }: Props) {
  const [search, setSearch] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editing, setEditing] = useState<any>(null);
  const filtered = suppliers.filter(s => (s.name||'').toLowerCase().includes(search.toLowerCase()) || (s.phone||'').includes(search));
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); onSave?.(editing); setShowModal(false); setEditing(null); };
  return (
    <div className="flex flex-col w-full pb-10">
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-6">
        <div><h1 className="text-3xl font-bold text-gray-800 font-serif mb-1">Quản lý Nhà cung cấp</h1><p className="text-sm text-gray-500">Quản lý hệ sinh thái đối tác cung cấp hàng may mặc cao cấp.</p></div>
        <button onClick={()=>{setEditing({}); setShowModal(true);}} className="flex items-center gap-2 px-5 py-2.5 bg-orange-700 text-white rounded-xl text-sm font-bold shadow-md hover:bg-orange-800"><Icon name="add_business" className="text-base" /> Thêm NCC</button>
      </div>
      <div className="bg-white border border-gray-100 rounded-2xl shadow-sm overflow-hidden">
        <div className="flex gap-3 p-4 border-b border-gray-100"><div className="relative flex-1 max-w-sm"><Icon name="search" className="absolute left-3 top-2.5 text-gray-400 text-xl" /><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm focus:outline-none focus:border-orange-400" placeholder="Tìm tên NCC, SĐT..."/></div></div>
        <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-400 text-xs font-bold uppercase tracking-wider border-b border-gray-100"><tr><th className="py-4 px-5">Mã NCC</th><th className="py-4 px-5">Tên nhà cung cấp</th><th className="py-4 px-5">Điện thoại</th><th className="py-4 px-5">Địa chỉ</th><th className="py-4 px-5 text-right">Thao tác</th></tr></thead><tbody className="text-gray-800 divide-y divide-gray-50">{filtered.map((s,idx)=>(<tr key={idx} className="hover:bg-orange-50/30 transition-colors group"><td className="py-4 px-5 font-bold text-orange-700">#{String(s.id||idx).padStart(3,'0')}</td><td className="py-4 px-5 font-semibold">{s.name||'Nhà cung cấp'}</td><td className="py-4 px-5 text-gray-500">{s.phone||'—'}</td><td className="py-4 px-5 text-gray-500">{s.address||'—'}</td><td className="py-4 px-5 text-right"><div className="flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={()=>{setEditing(s); setShowModal(true);}} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-700"><Icon name="edit" className="text-lg" /></button><button onClick={()=>onDelete?.(s.id)} className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-red-600"><Icon name="delete" className="text-lg" /></button></div></td></tr>))}{filtered.length===0&&<tr><td colSpan={5} className="py-12 text-center text-gray-400"><Icon name="store" className="text-5xl block mb-2 opacity-30" />Không có NCC nào.</td></tr>}</tbody></table></div>
        <div className="p-4 flex items-center justify-between text-sm text-gray-500 border-t border-gray-100"><span>Hiển thị {filtered.length}/{suppliers.length} NCC</span></div>
      </div>
      {showModal&&(<div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-2xl w-full max-w-xl p-6"><h2 className="text-xl font-bold text-gray-800 mb-4">{editing?.id?'Cập nhật':'Thêm'} NCC</h2><form onSubmit={handleSubmit} className="flex flex-col gap-4"><div><label className="block text-sm font-bold text-gray-700 mb-1">Tên NCC:</label><input value={editing?.name||''} onChange={e=>setEditing({...editing,name:e.target.value})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm" required/></div><div><label className="block text-sm font-bold text-gray-700 mb-1">Điện thoại:</label><input value={editing?.phone||''} onChange={e=>setEditing({...editing,phone:e.target.value})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"/></div><div><label className="block text-sm font-bold text-gray-700 mb-1">Địa chỉ:</label><input value={editing?.address||''} onChange={e=>setEditing({...editing,address:e.target.value})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm"/></div><div className="flex justify-end gap-3 mt-4 pt-4 border-t border-gray-100"><button type="button" onClick={()=>setShowModal(false)} className="px-5 py-2.5 bg-gray-100 text-gray-700 font-semibold rounded-lg">Hủy</button><button type="submit" className="px-5 py-2.5 bg-orange-700 text-white font-bold rounded-lg">Lưu</button></div></form></div></div>)}
    </div>
  );
}
