import { useCallback, useEffect, useState } from 'react';
import { ApiError, apiRequest, clearSession } from '../api';

type Voucher = { id:number;code:string;type:'FIXED'|'PERCENT';value:number;maxDiscount:number|null;minSubtotal:number;startsAt:string;endsAt:string;isActive:boolean;totalLimit:number|null;perCustomerLimit:number;usedCount:number;scope:'ALL'|'PRODUCT'|'CATEGORY';scopeIds:number[];version:number };
type Option = { id:number;name:string };
type Form = Omit<Voucher,'id'|'version'|'usedCount'|'value'|'maxDiscount'|'minSubtotal'|'totalLimit'|'perCustomerLimit'> & {id?:number;version?:number;value:string;maxDiscount:string;minSubtotal:string;totalLimit:string;perCustomerLimit:string};
type Usage = {id:number;customerId:number;orders:number[];discount:number;status:string;createdAt:string};
const inputClass='mt-1 w-full border rounded-lg p-2.5 bg-white disabled:opacity-50';
const price=(n:number)=>`${n.toLocaleString('vi-VN')} đ`;
const localDate=(value:string)=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const initial=():Form=>({code:'',type:'FIXED',value:'',maxDiscount:'',minSubtotal:'0',startsAt:localDate(new Date().toISOString()),endsAt:localDate(new Date(Date.now()+7*86400000).toISOString()),isActive:true,totalLimit:'',perCustomerLimit:'1',scope:'ALL',scopeIds:[]});
const failure=(cause:unknown)=>{if(cause instanceof ApiError&&cause.status===401){clearSession();window.location.href='/login';}return cause instanceof Error?cause.message:'Không thể quản lý voucher.';};

export default function VouchersView({products,categories}:{products:Option[];categories:Option[]}) {
  const [items,setItems]=useState<Voucher[]>([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[query,setQuery]=useState('');
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<Form|null>(null),[formError,setFormError]=useState('');
  const [usageFor,setUsageFor]=useState<Voucher|null>(null),[usagePage,setUsagePage]=useState(1),[usagePages,setUsagePages]=useState(1),[usages,setUsages]=useState<Usage[]>([]),[usageLoading,setUsageLoading]=useState(false),[usageError,setUsageError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const next=await apiRequest(`/vouchers?page=${page}&pageSize=20&search=${encodeURIComponent(query)}`);setItems(next.items);setPages(Math.max(1,next.totalPages));setTotal(next.total);}catch(cause){setError(failure(cause));}finally{setLoading(false);}},[page,query]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{let active=true;if(!usageFor)return;void Promise.resolve().then(async()=>{if(!active)return;setUsageLoading(true);setUsageError('');try{const next=await apiRequest(`/vouchers/${usageFor.id}/usage?page=${usagePage}&pageSize=20`);if(active){setUsages(next.items);setUsagePages(Math.max(1,next.totalPages));}}catch(cause){if(active)setUsageError(failure(cause));}finally{if(active)setUsageLoading(false);}});return()=>{active=false;};},[usageFor,usagePage]);
  const edit=(voucher:Voucher)=>{setForm({...voucher,value:String(voucher.value),maxDiscount:voucher.maxDiscount===null?'':String(voucher.maxDiscount),minSubtotal:String(voucher.minSubtotal),totalLimit:voucher.totalLimit===null?'':String(voucher.totalLimit),perCustomerLimit:String(voucher.perCustomerLimit),startsAt:localDate(voucher.startsAt),endsAt:localDate(voucher.endsAt)});setFormError('');};
  const integer=(value:string,label:string)=>{if(!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value)))throw new Error(`${label} cần số nguyên không âm.`);return Number(value);};
  const save=async(event:React.FormEvent)=>{event.preventDefault();if(!form||busy)return;setBusy(true);setFormError('');try{
    if(!form.startsAt||!form.endsAt||!Number.isFinite(Date.parse(form.startsAt))||!Number.isFinite(Date.parse(form.endsAt)))throw new Error('Nhập thời gian bắt đầu/kết thúc hợp lệ.');
    const body={...form,expectedVersion:form.version,value:integer(form.value,'Mức giảm'),maxDiscount:form.maxDiscount===''?null:integer(form.maxDiscount,'Giảm tối đa'),minSubtotal:integer(form.minSubtotal,'Đơn tối thiểu'),totalLimit:form.totalLimit===''?null:integer(form.totalLimit,'Tổng lượt'),perCustomerLimit:integer(form.perCustomerLimit,'Lượt mỗi khách'),startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString()};
    await apiRequest(`/vouchers${form.id?`/${form.id}`:''}`,{method:form.id?'PUT':'POST',body:JSON.stringify(body)});setForm(null);setNotice('Đã lưu voucher vào database.');await load();
  }catch(cause){setFormError(failure(cause));}finally{setBusy(false);}};
  const pause=async(voucher:Voucher)=>{if(busy)return;setBusy(true);setError('');try{await apiRequest(`/vouchers/${voucher.id}`,{method:'PUT',body:JSON.stringify({expectedVersion:voucher.version,isActive:!voucher.isActive})});setNotice(voucher.isActive?'Đã ngừng voucher; đơn cũ giữ nguyên.':'Đã bật voucher.');await load();}catch(cause){setError(failure(cause));}finally{setBusy(false);}};
  const field=(key:keyof Form,value:unknown)=>setForm(current=>current?{...current,[key]:value}:current);
  return <section className="space-y-5">
    <header className="flex flex-wrap gap-3 justify-between"><div><h1 className="font-serif text-3xl font-bold">Voucher & ưu đãi</h1><p className="text-sm text-gray-500 mt-2">Một mã mỗi checkout. Giảm tiền hàng đủ điều kiện, không giảm phí giao. Hủy toàn bộ mới hoàn lượt.</p></div><button className="bg-red-700 text-white rounded-lg px-4 py-2" disabled={busy} onClick={()=>{setForm(initial());setFormError('');}}>Tạo voucher</button></header>
    {notice&&<p role="status" className="p-3 border rounded-lg bg-white">{notice}</p>}{error&&<p role="alert" className="p-3 rounded-lg bg-red-50 text-red-700">{error}</p>}
    {form&&<form onSubmit={event=>void save(event)} className="bg-white border rounded-2xl p-4 sm:p-6 space-y-4" aria-label="Thông tin voucher">
      <h2 className="font-bold text-xl">{form.id?'Sửa voucher':'Voucher mới'}</h2>
      <fieldset disabled={busy} className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 disabled:opacity-60">
        <label className="text-sm font-semibold">Mã voucher<input className={inputClass} value={form.code} maxLength={40} required onChange={e=>field('code',e.target.value.toUpperCase())}/></label>
        <label className="text-sm font-semibold">Loại giảm<select className={inputClass} value={form.type} onChange={e=>field('type',e.target.value)}><option value="FIXED">Số tiền VND</option><option value="PERCENT">Phần trăm</option></select></label>
        <label className="text-sm font-semibold">Mức giảm {form.type==='PERCENT'?'(%)':'(đ)'}<input className={inputClass} type="number" step="1" min="1" required value={form.value} onChange={e=>field('value',e.target.value)}/></label>
        <label className="text-sm font-semibold">Giảm tối đa (đ)<input className={inputClass} type="number" step="1" min="1" required={form.type==='PERCENT'} placeholder={form.type==='PERCENT'?'Bắt buộc':'Không giới hạn'} value={form.maxDiscount} onChange={e=>field('maxDiscount',e.target.value)}/></label>
        <label className="text-sm font-semibold">Đơn tối thiểu (đ)<input className={inputClass} type="number" step="1" min="0" required value={form.minSubtotal} onChange={e=>field('minSubtotal',e.target.value)}/></label>
        <label className="text-sm font-semibold">Tổng lượt tối đa<input className={inputClass} type="number" step="1" min="1" placeholder="Không giới hạn" value={form.totalLimit} onChange={e=>field('totalLimit',e.target.value)}/></label>
        <label className="text-sm font-semibold">Lượt mỗi khách<input className={inputClass} type="number" step="1" min="1" required value={form.perCustomerLimit} onChange={e=>field('perCustomerLimit',e.target.value)}/></label>
        <label className="text-sm font-semibold">Bắt đầu (giờ máy)<input className={inputClass} type="datetime-local" required value={form.startsAt} onChange={e=>field('startsAt',e.target.value)}/></label>
        <label className="text-sm font-semibold">Kết thúc (giờ máy)<input className={inputClass} type="datetime-local" required value={form.endsAt} onChange={e=>field('endsAt',e.target.value)}/></label>
        <label className="text-sm font-semibold">Phạm vi<select className={inputClass} value={form.scope} onChange={e=>setForm({...form,scope:e.target.value as Form['scope'],scopeIds:[]})}><option value="ALL">Toàn bộ tiền hàng</option><option value="PRODUCT">Sản phẩm được chọn</option><option value="CATEGORY">Danh mục được chọn</option></select></label>
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={e=>field('isActive',e.target.checked)}/> Cho phép áp dụng</label>
        {form.scope!=='ALL'&&<div className="sm:col-span-2 lg:col-span-3"><p className="text-sm font-semibold mb-2">Chọn {form.scope==='PRODUCT'?'sản phẩm':'danh mục'} đủ điều kiện</p><div className="max-h-52 overflow-y-auto border rounded-lg p-3 grid sm:grid-cols-2 gap-2">{(form.scope==='PRODUCT'?products:categories).map(option=><label className="flex items-center gap-2 text-sm" key={option.id}><input type="checkbox" checked={form.scopeIds.includes(option.id)} onChange={e=>field('scopeIds',e.target.checked?[...form.scopeIds,option.id]:form.scopeIds.filter(id=>id!==option.id))}/>{option.name}</label>)}</div></div>}
      </fieldset>
      {formError&&<p role="alert" className="text-red-700 bg-red-50 p-3 rounded-lg">{formError}</p>}
      <div className="flex flex-wrap gap-3"><button className="bg-red-700 text-white rounded-lg px-4 py-2 disabled:opacity-50" disabled={busy}>{busy?'Đang lưu…':'Lưu voucher'}</button><button type="button" className="border rounded-lg px-4 py-2" disabled={busy} onClick={()=>setForm(null)}>Đóng form</button><button type="button" className="border rounded-lg px-4 py-2" disabled={busy} onClick={()=>{setForm(null);void load();}}>Tải dữ liệu mới</button></div>
    </form>}
    <form className="flex gap-3" onSubmit={e=>{e.preventDefault();setQuery(search.trim());setPage(1);}}><input aria-label="Tìm voucher" className="border rounded-lg p-2 flex-1 min-w-0" placeholder="Tìm mã voucher" value={search} onChange={e=>setSearch(e.target.value)}/><button className="border rounded-lg px-4 py-2 bg-white">Tìm</button><button type="button" className="border rounded-lg px-4 py-2 bg-white" disabled={loading} onClick={()=>void load()}>Cập nhật</button></form>
    <div className="bg-white border rounded-xl overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-gray-50"><tr>{['Mã & hiệu lực','Giảm giá','Lượt dùng','Phạm vi','Thao tác'].map(title=><th key={title} className="p-4">{title}</th>)}</tr></thead><tbody className="divide-y">{!loading&&items.map(v=><tr key={v.id}><td className="p-4 font-semibold">{v.code}<p className="font-normal text-xs text-gray-500 mt-1">{v.isActive?'Đang bật':'Đã ngừng'} · {new Date(v.endsAt).toLocaleString('vi-VN')}</p></td><td className="p-4">{v.type==='PERCENT'?`${v.value}%`:price(v.value)}{v.maxDiscount!==null&&<p className="text-xs text-gray-500">Tối đa {price(v.maxDiscount)}</p>}<p className="text-xs">Đơn từ {price(v.minSubtotal)}</p></td><td className="p-4">{v.usedCount}/{v.totalLimit??'∞'}<p className="text-xs text-gray-500">{v.perCustomerLimit} lượt/khách</p></td><td className="p-4">{v.scope==='ALL'?'Toàn bộ':`${v.scopeIds.length} ${v.scope==='PRODUCT'?'sản phẩm':'danh mục'}`}</td><td className="p-4"><div className="flex flex-wrap gap-3"><button disabled={busy} className="text-red-700 underline" onClick={()=>edit(v)}>Sửa</button><button disabled={busy} className="underline" onClick={()=>void pause(v)}>{v.isActive?'Ngừng':'Bật lại'}</button><button className="underline" onClick={()=>{setUsageFor(v);setUsagePage(1);setUsages([]);}}>Lượt sử dụng</button></div></td></tr>)}{loading&&<tr><td colSpan={5} className="p-8 text-center">Đang tải voucher…</td></tr>}{!loading&&!items.length&&<tr><td colSpan={5} className="p-8 text-center text-gray-500">Chưa có voucher phù hợp.</td></tr>}</tbody></table></div>
    <div className="flex justify-between gap-3 text-sm items-center"><span>{total} voucher · Trang {page}/{pages}</span><div className="flex gap-2"><button className="border rounded-lg p-2" disabled={loading||page<=1} onClick={()=>setPage(p=>p-1)}>Trước</button><button className="border rounded-lg p-2" disabled={loading||page>=pages} onClick={()=>setPage(p=>p+1)}>Sau</button></div></div>
    {usageFor&&<div className="bg-white border rounded-xl p-4 space-y-3"><div className="flex justify-between"><h2 className="font-bold">Lượt sử dụng · {usageFor.code}</h2><button className="underline" onClick={()=>setUsageFor(null)}>Đóng lịch sử</button></div>{usageError&&<p role="alert" className="text-red-700">{usageError}</p>}{usageLoading?<p>Đang tải lượt dùng…</p>:!usages.length?<p className="text-sm text-gray-500">Chưa có lượt sử dụng.</p>:<ul className="divide-y">{usages.map(u=><li key={u.id} className="py-3 text-sm">Khách #{u.customerId} · Đơn {u.orders.map(id=>`#${id}`).join(', ')} · Giảm {price(u.discount)}<p className="text-gray-500">{u.status==='RELEASED'?'Đã hoàn lượt do hủy toàn bộ':'Đang tính lượt'} · {new Date(u.createdAt).toLocaleString('vi-VN')}</p></li>)}</ul>}<div className="flex gap-3 items-center text-sm"><button className="border rounded-lg p-2" disabled={usageLoading||usagePage<=1} onClick={()=>setUsagePage(p=>p-1)}>Lượt trước</button><span>{usagePage}/{usagePages}</span><button className="border rounded-lg p-2" disabled={usageLoading||usagePage>=usagePages} onClick={()=>setUsagePage(p=>p+1)}>Lượt sau</button></div></div>}
  </section>;
}
